#! /usr/bin/perl

# Copyright 2014 Nikita Pichugin
#
# This file is part of My Game Library 2.
# 
# My Game Library 2 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# My Game Library 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with My Game Library 2.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;
use Getopt::Long;
use FindBin;
use lib "$FindBin::Bin";
use MGDB;

sub print_usage
{
    print "Usage: lookup";
    print " --db DBPATH [--separator (n|0|s)] [--query QUERY]\n";
    return 1;
}

my $db_path = "";
my $separator = "n";
my $query = ".*";
my $need_help = 0;
GetOptions ("db=s"        => \$db_path,
            "separator=s" => \$separator,
            "query=s"     => \$query,
            "help|usage"  => \$need_help) or exit 1;

print_usage and exit 0 if $need_help;
print_usage and exit 1 if $db_path eq "";

if ($separator eq "n")
{
    $separator = "\n";
}
elsif ($separator eq "0")
{
    $separator = "\0";
}
elsif ($separator eq "s")
{
    $separator = " ";
}
else
{
    print_usage and exit 1;
}

my @db = MGDB::load_db $db_path;
@db = MGDB::lookup_db \@db, $query;
my @paths = map { $_->{"_PATH"} } @db;
print join $separator, @paths;

